name        = Tokyo Night
mode        = dark
bg          = #1a1b26
bg_alt      = #1f2335
bg_hl       = #292e42
fg          = #c0caf5
fg_dim      = #565f89
accent      = #7aa2f7
accent2     = #bb9af7
red         = #f7768e
orange      = #ff9e64
yellow      = #e0af68
green       = #9ece6a
cyan        = #7dcfff
blue        = #7aa2f7
purple      = #bb9af7
