#!/usr/bin/env python3
"""Extract Hyprland's Lua config API from its source tree into tests/hypr-api.lua.

The test harness (tests/check-hypr-config.lua) loads Lumen's Hyprland config
against a stub `hl` table built from this data, so typos in option names,
rule fields or dispatchers fail CI instead of a user's session.

    python3 tests/gen-hypr-api.py /path/to/Hyprland/src v0.56.2 > tests/hypr-api.lua
"""
import re
import sys
from pathlib import Path

src = Path(sys.argv[1])
version = sys.argv[2] if len(sys.argv) > 2 else "unknown"


def read(rel):
    return (src / rel).read_text()


def block_names(text, marker):
    start = text.index(marker)
    end = text.index("};", start)
    return re.findall(r'\{\s*"([a-z_0-9]+)"', text[start:end])


cfg = read("config/values/ConfigValues.cpp")
config = sorted({m.replace(":", ".") for m in re.findall(r'MS<\w+>\(\s*"([^"]+)"', cfg)})

internal = read("config/lua/bindings/LuaBindingsInternal.hpp")
rules = read("config/lua/bindings/LuaBindingsConfigRules.cpp")
window_effects = block_names(internal, "WINDOW_RULE_EFFECT_DESCS[]")
layer_effects = block_names(rules, "LAYER_RULE_EFFECT_DESCS[]")
workspace_fields = block_names(rules, "WORKSPACE_RULE_FIELDS[]")
monitor_fields = block_names(rules, "MONITOR_FIELDS[]")
device_fields = block_names(rules, "DEVICE_FIELDS[]")

rule_cpp = read("desktop/rule/Rule.cpp")
match_props = re.findall(r'\{RULE_PROP_\w+, "([a-z_]+)"\}', rule_cpp)

# Dispatchers: walk registerDispatcherBindings, tracking nested tables.
dsp = read("config/lua/bindings/LuaBindingsDispatchers.cpp")
body = dsp[dsp.index("void Internal::registerDispatcherBindings"):]
dispatchers, pending = [], []
for line in body.splitlines():
    if m := re.search(r'setFn\(L, "([a-z_]+)"', line):
        pending.append(m.group(1))
    elif m := re.search(r'lua_setfield\(L, -2, "([a-z_]+)"\)', line):
        if m.group(1) == "dsp":
            dispatchers += pending
            break
        dispatchers += [f"{m.group(1)}.{n}" for n in pending]
        pending = []

toplevel = set()
for f in (src / "config/lua").rglob("*.cpp"):
    t = f.read_text()
    for name in re.findall(r'(?:setFn|setMgrFn)\(L,(?: mgr,)? "([a-z_]+)"', t):
        toplevel.add(name)
toplevel -= set(n.split(".")[-1] for n in dispatchers) - {"exec_cmd"}

anim = set()
for f in src.rglob("*.cpp"):
    anim.update(re.findall(r'(?:createNode|addNode)\("([A-Za-z_]+)"', f.read_text()))

bind_opts = re.findall(r'getBool\("([a-z_]+)"\)', read("config/lua/bindings/LuaBindingsToplevel.cpp"))
events = sorted(set(re.findall(r'"((?:hyprland|window|workspace|monitor|config|keybinds|layer|screenshare|submap)\.[a-z_]+)"',
                                "".join(p.read_text() for p in (src / "config/lua").rglob("*.cpp")))))


def lua_list(name, items):
    inner = ", ".join(f'"{i}"' for i in items)
    return f"{name} = {{ {inner} }},"


print(f"-- Generated by tests/gen-hypr-api.py from Hyprland {version}. Do not edit.")
print("return {")
print(f'version = "{version}",')
for name, items in [
    ("config", config), ("window_effects", window_effects), ("layer_effects", layer_effects),
    ("workspace_fields", workspace_fields), ("monitor_fields", monitor_fields),
    ("device_fields", device_fields), ("match_props", match_props), ("dispatchers", dispatchers),
    ("toplevel", sorted(toplevel)), ("animations", sorted(anim)),
    ("bind_options", bind_opts + ["description", "desc", "click", "drag", "mouse", "device"]),
    ("events", events),
]:
    print(lua_list(name, items))
print("}")
