name        = Catppuccin Mocha
mode        = dark
bg          = #1e1e2e
bg_alt      = #181825
bg_hl       = #313244
fg          = #cdd6f4
fg_dim      = #7f849c
accent      = #cba6f7
accent2     = #89b4fa
red         = #f38ba8
orange      = #fab387
yellow      = #f9e2af
green       = #a6e3a1
cyan        = #94e2d5
blue        = #89b4fa
purple      = #cba6f7
term_black        = #45475a
term_bright_black = #585b70
term_white        = #bac2de
term_bright_white = #a6adc8
