name        = Catppuccin Latte
mode        = light
bg          = #eff1f5
bg_alt      = #e6e9ef
bg_hl       = #ccd0da
fg          = #4c4f69
fg_dim      = #8c8fa1
accent      = #8839ef
accent2     = #1e66f5
red         = #d20f39
orange      = #fe640b
yellow      = #df8e1d
green       = #40a02b
cyan        = #179299
blue        = #1e66f5
purple      = #8839ef
term_black        = #5c5f77
term_bright_black = #6c6f85
term_white        = #acb0be
term_bright_white = #bcc0cc
