-- Apps to start when you log in.
--
-- hl.on("hyprland.start", function()
--     hl.exec_cmd("anarch-launch -- signal-desktop --start-in-tray")
--     hl.exec_cmd("anarch-launch -- spotify", { workspace = "9 silent" })
-- end)
