-- Your key bindings. They are added after an4rch's (SUPER + / lists them all).
--
-- Replace a default:
--   hl.unbind("SUPER + B")
--   hl.bind("SUPER + B", hl.dsp.exec_cmd("anarch-launch -- chromium"), { description = "Chromium" })
--
-- Launch an app (anarch-launch runs it as a proper systemd scope):
--   hl.bind("SUPER + O", hl.dsp.exec_cmd("anarch-launch -- obsidian"), { description = "Notes" })
--
-- Open a website as an app window:
--   hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("anarch-webapp https://music.youtube.com"), { description = "Music" })
--
-- Run Lua directly:
--   hl.bind("SUPER + CTRL + O", function()
--       hl.dispatch(hl.dsp.window.float({ action = "toggle" }))
--       hl.dispatch(hl.dsp.window.center())
--   end, { description = "Float and centre" })
