name        = Rosé Pine
mode        = dark
bg          = #191724
bg_alt      = #1f1d2e
bg_hl       = #26233a
fg          = #e0def4
fg_dim      = #6e6a86
accent      = #c4a7e7
accent2     = #ebbcba
red         = #eb6f92
orange      = #ebbcba
yellow      = #f6c177
green       = #31748f
cyan        = #9ccfd8
blue        = #9ccfd8
purple      = #c4a7e7
