# Generated by anarch-theme from "{{name}}".
[colors.primary]
background = "{{bg}}"
foreground = "{{fg}}"

[colors.cursor]
cursor = "{{accent}}"
text = "{{bg}}"

[colors.selection]
background = "{{bg_hl}}"
text = "{{fg}}"

[colors.normal]
black = "{{term_black}}"
red = "{{red}}"
green = "{{green}}"
yellow = "{{yellow}}"
blue = "{{blue}}"
magenta = "{{purple}}"
cyan = "{{cyan}}"
white = "{{term_white}}"

[colors.bright]
black = "{{term_bright_black}}"
red = "{{red}}"
green = "{{green}}"
yellow = "{{yellow}}"
blue = "{{blue}}"
magenta = "{{purple}}"
cyan = "{{cyan}}"
white = "{{term_bright_white}}"
