/* Generated by lumen-theme from "{{name}}". Used by Lumen's own apps
   (Start menu, App Store) on top of libadwaita. */
@define-color lumen_bg      {{bg}};
@define-color lumen_bg_alt  {{bg_alt}};
@define-color lumen_bg_hl   {{bg_hl}};
@define-color lumen_fg      {{fg}};
@define-color lumen_fg_dim  {{fg_dim}};
@define-color lumen_accent  {{accent}};
@define-color lumen_accent2 {{accent2}};
@define-color lumen_red     {{red}};
@define-color lumen_green   {{green}};
@define-color lumen_yellow  {{yellow}};

/* libadwaita named colours, so stock widgets match the theme too. */
@define-color accent_bg_color     {{accent}};
@define-color accent_color        {{accent}};
@define-color accent_fg_color     {{bg}};
@define-color window_bg_color     {{bg}};
@define-color window_fg_color     {{fg}};
@define-color view_bg_color       {{bg}};
@define-color view_fg_color       {{fg}};
@define-color headerbar_bg_color  {{bg_alt}};
@define-color headerbar_fg_color  {{fg}};
@define-color sidebar_bg_color    {{bg_alt}};
@define-color sidebar_fg_color    {{fg}};
@define-color card_bg_color       {{bg_alt}};
@define-color card_fg_color       {{fg}};
@define-color popover_bg_color    {{bg_alt}};
@define-color popover_fg_color    {{fg}};
@define-color dialog_bg_color     {{bg_alt}};
@define-color dialog_fg_color     {{fg}};
@define-color destructive_bg_color {{red}};
@define-color success_bg_color    {{green}};
