# Generated by anarch-theme from "{{name}}".
[main]
icon-theme={{icon_theme}}

[colors]
background={{bg_alt.hex}}f2
text={{fg.hex}}ff
prompt={{accent.hex}}ff
placeholder={{fg_dim.hex}}ff
input={{fg.hex}}ff
match={{accent.hex}}ff
selection={{bg_hl.hex}}ff
selection-text={{fg.hex}}ff
selection-match={{accent2.hex}}ff
counter={{fg_dim.hex}}ff
border={{accent.hex}}cc
