# Generated by lumen-theme from "{{name}}". Sourced by the shell.
export FZF_DEFAULT_OPTS="--height=60% --layout=reverse --border=rounded --info=inline-right --pointer='▌' --marker='┃' --prompt='❯ ' \
  --color=bg+:{{bg_hl}},bg:-1,fg:{{fg}},fg+:{{fg}},hl:{{accent}},hl+:{{accent2}} \
  --color=border:{{bg_hl}},header:{{fg_dim}},info:{{fg_dim}},marker:{{accent2}},pointer:{{accent}},prompt:{{accent}},spinner:{{accent2}},label:{{fg_dim}}"
