/* Generated by anarch-theme from "{{name}}": the login screen's colours.
   Copied to /var/lib/lumen/login by `anarch-login sync`. */
@define-color g_bg     {{bg}};
@define-color g_card   {{bg_alt}};
@define-color g_field  {{bg_hl}};
@define-color g_fg     {{fg}};
@define-color g_dim    {{fg_dim}};
@define-color g_accent {{accent}};
@define-color g_accent_fg {{accent_fg}};
@define-color g_red    {{red}};
