-- Generated by anarch-theme from the "{{name}}" palette. Changes here are
-- overwritten on the next theme switch; use `anarch-theme new <name>` to make
-- your own theme instead.

local palette = {
    bg      = "{{bg.hex}}",
    bg_alt  = "{{bg_alt.hex}}",
    bg_hl   = "{{bg_hl.hex}}",
    fg      = "{{fg.hex}}",
    fg_dim  = "{{fg_dim.hex}}",
    accent  = "{{accent.hex}}",
    accent2 = "{{accent2.hex}}",
    red     = "{{red.hex}}",
    yellow  = "{{yellow.hex}}",
    green   = "{{green.hex}}",
}

hl.config({
    general = {
        col = {
            active_border   = { colors = { "rgba({{accent.hex}}ee)", "rgba({{accent2.hex}}ee)" }, angle = 45 },
            inactive_border = "rgba({{bg_hl.hex}}aa)",
        },
    },
    group = {
        col = {
            border_active   = { colors = { "rgba({{accent2.hex}}ee)", "rgba({{accent.hex}}ee)" }, angle = 45 },
            border_inactive = "rgba({{bg_hl.hex}}aa)",
            border_locked_active = "rgba({{orange.hex}}ee)",
        },
        groupbar = {
            text_color          = "rgb({{bg.hex}})",
            text_color_inactive = "rgb({{fg.hex}})",
            col = {
                active   = "rgba({{accent.hex}}ee)",
                inactive = "rgba({{bg_hl.hex}}ee)",
            },
        },
    },
    misc = {
        background_color = "rgb({{bg.hex}})",
    },
})

return palette
