# Generated by lumen-theme from "{{name}}".
$bg      = rgb({{bg.hex}})
$surface = rgba({{bg_alt.hex}}d9)
$fg      = rgb({{fg.hex}})
$fg_dim  = rgb({{fg_dim.hex}})
$accent  = rgb({{accent.hex}})
$accent2 = rgb({{accent2.hex}})
$red     = rgb({{red.hex}})
$yellow  = rgb({{yellow.hex}})
