# Generated by anarch-theme from "{{name}}".
background-color={{bg_alt}}f2
text-color={{fg}}
border-color={{bg_hl}}
progress-color=over {{accent}}66

[urgency=critical]
border-color={{red}}

[app-name=Reminder]
border-color={{yellow}}
