/* Generated by anarch-theme from "{{name}}": the login screen (ReGreet).
   Copied to /var/lib/lumen/login by `anarch-login sync`. */
* {
  font-family: "Inter", sans-serif;
}

window {
  background-color: {{bg}};
  color: {{fg}};
}

/* ReGreet's boxes: the login form and the clock (not the hidden message box). */
overlay > frame {
  padding: 20px;
  border-radius: 24px;
  background-color: alpha({{bg_alt}}, 0.84);
  border: 1px solid alpha({{accent}}, 0.35);
  box-shadow: 0 24px 70px alpha(black, 0.55);
}

label {
  color: {{fg}};
}

entry,
dropdown > button,
combobox button {
  min-height: 40px;
  border-radius: 14px;
  background: alpha({{bg_hl}}, 0.92);
  color: {{fg}};
  border: 1px solid alpha({{fg}}, 0.08);
}

entry:focus-within {
  border-color: {{accent}};
  box-shadow: 0 0 0 3px alpha({{accent}}, 0.30);
}

button {
  min-height: 38px;
  border-radius: 14px;
  background: alpha({{bg_hl}}, 0.92);
  color: {{fg}};
}

button:hover {
  background: alpha({{accent}}, 0.22);
}

button.suggested-action {
  background-image: linear-gradient(135deg, {{accent}}, {{accent2}});
  color: {{bg}};
  font-weight: 700;
}

button.destructive-action {
  background: {{red}};
  color: {{bg}};
}

infobar,
.error {
  color: {{red}};
}
