# Generated by anarch-theme from "{{name}}".
# To customise the prompt layout, copy this file somewhere, edit it and point
# STARSHIP_CONFIG at your copy in ~/.config/lumen/shell.zsh.
"$schema" = "https://starship.rs/config-schema.json"
palette = "lumen"
add_newline = true
format = "$directory$git_branch$git_status$python$nodejs$rust$golang$cmd_duration$line_break$character"

[palettes.lumen]
accent = "{{accent}}"
accent2 = "{{accent2}}"
dim = "{{fg_dim}}"
red = "{{red}}"
green = "{{green}}"
yellow = "{{yellow}}"

[directory]
style = "bold accent"
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = " "
style = "accent2"
format = "[$symbol$branch]($style) "

[git_status]
style = "yellow"
format = "([$all_status$ahead_behind]($style) )"

[cmd_duration]
min_time = 2000
style = "dim"
format = "[took $duration]($style) "

[python]
symbol = " "
style = "dim"

[nodejs]
symbol = " "
style = "dim"

[rust]
symbol = " "
style = "dim"

[golang]
symbol = " "
style = "dim"

[character]
success_symbol = "[❯](bold accent)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
