/* Generated by anarch-theme from "{{name}}". */
@define-color bg      {{bg}};
@define-color bg_alt  {{bg_alt}};
@define-color bg_hl   {{bg_hl}};
@define-color fg      {{fg}};
@define-color fg_dim  {{fg_dim}};
@define-color accent  {{accent}};
@define-color accent2 {{accent2}};
@define-color red     {{red}};
@define-color orange  {{orange}};
@define-color yellow  {{yellow}};
@define-color green   {{green}};
@define-color cyan    {{cyan}};
@define-color blue    {{blue}};
@define-color purple  {{purple}};
