name        = Nord
mode        = dark
bg          = #2e3440
bg_alt      = #3b4252
bg_hl       = #434c5e
fg          = #eceff4
fg_dim      = #7b869b
accent      = #88c0d0
accent2     = #81a1c1
red         = #bf616a
orange      = #d08770
yellow      = #ebcb8b
green       = #a3be8c
cyan        = #8fbcbb
blue        = #81a1c1
purple      = #b48ead
term_black        = #3b4252
term_bright_black = #4c566a
term_white        = #e5e9f0
term_bright_white = #eceff4
