name        = Everforest
mode        = dark
bg          = #2d353b
bg_alt      = #343f44
bg_hl       = #475258
fg          = #d3c6aa
fg_dim      = #859289
accent      = #a7c080
accent2     = #83c092
red         = #e67e80
orange      = #e69875
yellow      = #dbbc7f
green       = #a7c080
cyan        = #83c092
blue        = #7fbbb3
purple      = #d699b6
